# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BjvQeiBfZ_cXsfPA-jLDGIriR9z_7y7-
"""

##if elseand condiaitonal loops#

marks= int(input('enter your marks'))
if marks>= 80:
  print('you will be part of A0 batch')
elif marks>=60 and marks<=80:
    print('you will be part of A1 batch')
elif marks>=40 and marks<60:
    print('you will be part of A2 batch')
else:
      print('you will be part of A3 batch')

#code 2 price

price= int(input('enter the price'))
price= int(input('enter the price'))
if price>1000:
  print(' i will purchase')
else:
    print(' i will not purchase')

price= int(input('enter the price'))

price= int(input('enter the price'))
if price>1000:
  print(' i will purchase')
  if price>5000:
    print(' i will not purchase')

price= int(input('enter the price'))
if price>1000:
  print(' i will purchase')
  if price>5000:
    print(' i will not purchase')
   elif price <2000:
      print(' its ok')

l=[1,2,3,4,5,6,7,8]
l[0]+1

#now suppose i want to take out each and every element and add a new no , we use loop

for i in l:
  print(i+1)

l1 = []
for i in l:
  print(i+1)

l1 = []
for i in l:
  print(i+1)
  l1.append(i+1)
l1

d= ['sudh', 'kumar', 'pwskills','course']

d1=[]
for i in d:
  print(i)
  d1.append(i.upper())

d1

c1= [4,5,6,7,8,89]
for i in c1:
  print(i)

c1= [4,5,6,7,8,89]
for i in c1:
  print(i+1)

c1= [4,5,6,7,8,89]
for i in c1:
  print(i+1)
  c1

c1= [4.5,5,6,7,9]
c1= []
for i in c1:
   print(i+1)
   c1.append(i+1)
c1

c1= [4.5,5,6,7,9]

c1= []
for i in c1:
   print(i+1)
   c1.append()
c1

x1= [ 'Jubin, agarwal, gwalior, india']

x1

x1= ['Jubin, agarwal, gwalior, india']
for i in x1:
  print(i)
  x1.append(d1.upper())
x1

x1

d1=[]
for i in d:
  print(i)
  d1.append(i.upper())

F=['jubin', 'agarwal', 'gwalior', 'india']

f

F

F1=[]
for i in F:
  print(i)
  F1.append(i.upper())
F1

F1

#to make two seperate list with one interger and one string

l= [ 1,2,3,4,5,6,'jubin','kumar', 3423, 23423.3432,'abc']

l1_num=[]
l2_str=[]
for i in l:
  if type(i)==int or type(i)==float:
    l1_num.append(i)
  else:
    l2_str.append(i)

l1_num

l2_str

